In [1]:
import numpy as np
import pygrib
import xarray as xr

In [4]:
data = '/home/prabu/Research/ECMWF_data/ownload2.grib'
gr = pygrib.open(data)
grb = gr.select()[0]
data1 = grb.values
print(data1)

[[258.13389587 258.20811462 258.26573181 258.25987244 258.24717712]
 [258.31163025 258.370224   258.38487244 258.35557556 258.37120056]
 [258.573349   258.67881775 258.71104431 258.71006775 258.75987244]
 [258.68663025 258.83702087 258.92588806 258.9874115  259.057724  ]
 [258.57920837 258.74424744 258.86729431 258.96495056 259.03623962]]
